#!/bin/bash
# dependency:   [mp3info] for id3 v1 only
#           or  [id3]     for id3 v1 v2 

echo $#;
if [ $# -eq 0 ];then
    echo "xiami_id3gen <title - artist - album mp3file>"
else
    for f in "$@"
    do
        echo $f
        str=$(echo $f  | sed -e 's/\.mp3//' -e 's/ - /@/g')
        title=$(echo $str | cut -d '@' -f 1)
        artist=$(echo $str | cut -d '@' -f 2)
        album=$(echo $str | cut -d '@' -f 3)

        #mp3info -t "$title" -l "$album" -a "$artist" "$f"
        id3 -2 -d -t "$title" -l "$album" -a "$artist" "$f"
    done
fi
